### PR TITLE
Fixed Back Button Crash.

### PR DESCRIPTION
**Pull request by MarkJoyce0111**
:)

### CODE REVIEW

**Comment by D1Matman** [comment]
I gave it a good test. Looks like its fixed when going between ViewByCountry and CountryInfo. But the same black screen issue still occurs on transitions between other scenes, when the Back button is pressed early while screen still transitioning.

**Comment by D1Matman** [comment]
image

I also encountered this error, when attempting to quickly go back and forth between CountryInfo and Rankings screen.

**Comment by MarkJoyce0111** [comment]
https://drive.google.com/open?id=1TMalgMDQY5ig6u04mACWwq-_DxMy5hmH

Download the above source above and see if you can make I crash the same way mate.

Sent from Mail for Windows 10

**Comment by MarkJoyce0111** [comment]
I found the problem

**Comment by MarkJoyce0111** [comment]
https://drive.google.com/open?id=1r7xSUtgbyFtzyyobrU_hGL-B44ALphAu

Ok this time I’m sure it’s fixed. Download this and see if you can crash it. I have created another pull request and the google drive file has been updated too. 
Regards Mark.

Sent from Mail for Windows 10

**Pull request closed without merging**
